# Cada pergunta: (texto, alternativa correta, [alternativas erradas]).
# A ordem define a pontuação: 2 fáceis (10), 2 médias (20), 2 difíceis (30).
AREAS = [
    # ---------------- Dados e IA ----------------
    {
        "group": "Dados e IA", "name": "Banco de Dados e SQL", "slug": "banco-de-dados-e-sql", "icon": "🗄️",
        "description": "Modelagem relacional, consultas SQL, transações e NoSQL.",
        "questions": [
            ("SQL é uma linguagem para:", "Consultar e manipular bancos de dados relacionais",
             ["Criar interfaces gráficas", "Editar imagens", "Compilar programas em C"]),
            ("Qual comando SQL busca dados de uma tabela?", "SELECT", ["INSERT", "DROP", "GRANT"]),
            ("Qual cláusula filtra as linhas de uma consulta?", "WHERE", ["ORDER BY", "GROUP BY", "LIMIT"]),
            ("O que é uma chave primária?", "Coluna que identifica cada registro de forma única",
             ["Coluna que guarda senhas", "Índice de texto completo", "Cópia de segurança da tabela"]),
            ("Qual JOIN retorna apenas as linhas com correspondência nas duas tabelas?", "INNER JOIN",
             ["LEFT JOIN", "FULL OUTER JOIN", "CROSS JOIN"]),
            ("O que significa o 'A' de ACID em transações?", "Atomicidade: a transação ocorre por completo ou não ocorre",
             ["Autenticação", "Acesso", "Alocação"]),
        ],
    },
    {
        "group": "Dados e IA", "name": "Ciência de Dados e Analytics", "slug": "ciencia-de-dados", "icon": "📊",
        "description": "Análise, estatística básica, ETL e visualização de dados.",
        "questions": [
            ("Qual biblioteca Python é muito usada para manipular tabelas de dados?", "pandas",
             ["Flask", "Pygame", "Django"]),
            ("O que é um dashboard?", "Painel visual com indicadores e gráficos",
             ["Um tipo de banco de dados", "Um vírus", "Um protocolo de rede"]),
            ("O que significa ETL?", "Extrair, Transformar e Carregar dados",
             ["Editar, Testar e Lançar", "Enviar, Traduzir e Listar", "Estimar, Treinar e Liberar"]),
            ("Qual é a mediana do conjunto [1, 3, 3, 6, 7, 8, 9]?", "6", ["3", "5,29", "7"]),
            ("O que mede o desvio padrão?", "A dispersão dos valores em torno da média",
             ["O maior valor do conjunto", "A quantidade de registros", "O valor mais frequente"]),
            ("Qual gráfico é mais adequado para mostrar a distribuição de uma variável numérica?", "Histograma",
             ["Gráfico de pizza", "Gráfico de dispersão de duas categorias", "Organograma"]),
        ],
    },
    {
        "group": "Dados e IA", "name": "Inteligência Artificial", "slug": "inteligencia-artificial", "icon": "🤖",
        "description": "Conceitos de IA, assistentes, linguagem natural e modelos de linguagem.",
        "questions": [
            ("A sigla IA significa:", "Inteligência Artificial",
             ["Interface Avançada", "Integração Analógica", "Instrução Automática"]),
            ("Qual é um exemplo de assistente virtual?", "Alexa ou Google Assistente",
             ["Photoshop", "Excel", "Bloco de Notas"]),
            ("O que é um chatbot?", "Programa que conversa com usuários por texto ou voz",
             ["Um antivírus", "Um tipo de processador", "Um formato de vídeo"]),
            ("O que é NLP?", "Processamento de linguagem natural",
             ["Navegação local por pacotes", "Rede de longa proximidade", "Numeração lógica de portas"]),
            ("O que é um LLM?", "Modelo de linguagem de grande porte treinado com muito texto",
             ["Um protocolo de rede local", "Um tipo de placa de vídeo", "Uma linguagem de marcação"]),
            ("O que é 'alucinação' em modelos de linguagem?", "Gerar informação plausível, porém incorreta ou inventada",
             ["Falha de hardware da GPU", "Erro de digitação do usuário", "Lentidão da internet"]),
        ],
    },
    {
        "group": "Dados e IA", "name": "Machine Learning", "slug": "machine-learning", "icon": "🧠",
        "description": "Aprendizado supervisionado e não supervisionado, treino e avaliação de modelos.",
        "questions": [
            ("Machine Learning é:", "Técnica em que sistemas aprendem padrões a partir de dados",
             ["Um tipo de hardware", "Programar cada regra manualmente", "Um sistema operacional"]),
            ("Qual biblioteca Python é comum em Machine Learning clássico?", "scikit-learn",
             ["Tkinter", "Requests", "Pillow"]),
            ("O aprendizado supervisionado utiliza dados:", "Rotulados, com a resposta esperada",
             ["Sem nenhum dado", "Apenas imagens", "Sempre criptografados"]),
            ("Qual é um exemplo de aprendizado não supervisionado?", "Agrupamento (clustering)",
             ["Classificação de spam com exemplos rotulados", "Previsão de preço com histórico rotulado",
              "Regressão linear com alvo conhecido"]),
            ("O que é overfitting?", "O modelo se ajusta demais ao treino e generaliza mal",
             ["O modelo é simples demais e erra tudo", "Excesso de dados de teste", "Falta de memória no servidor"]),
            ("Para que serve dividir os dados em conjuntos de treino e teste?",
             "Avaliar o desempenho do modelo em dados que ele não viu",
             ["Acelerar a internet", "Criptografar os dados", "Reduzir o tamanho do arquivo"]),
        ],
    },
    # ---------------- Infraestrutura ----------------
    {
        "group": "Infraestrutura", "name": "Redes de Computadores", "slug": "redes-de-computadores", "icon": "🌐",
        "description": "Protocolos, endereçamento IP, DNS, modelo OSI e TCP/IP.",
        "questions": [
            ("Qual protocolo é usado para navegar em páginas web com criptografia?", "HTTPS",
             ["FTP", "SMTP", "Telnet"]),
            ("O que o endereço IP identifica?", "Um dispositivo em uma rede",
             ["Um arquivo", "Um usuário de e-mail", "Uma senha"]),
            ("Qual é a função do DNS?", "Traduzir nomes de domínio em endereços IP",
             ["Criptografar o tráfego", "Distribuir energia", "Bloquear anúncios"]),
            ("Qual camada do modelo OSI é a de Transporte?", "Camada 4", ["Camada 2", "Camada 3", "Camada 7"]),
            ("Qual é a máscara de sub-rede equivalente a /24?", "255.255.255.0",
             ["255.255.0.0", "255.0.0.0", "255.255.255.128"]),
            ("Qual a principal diferença entre TCP e UDP?", "TCP é orientado à conexão e confiável; UDP não garante entrega",
             ["UDP é sempre mais seguro", "TCP não usa portas", "UDP exige handshake de três vias"]),
        ],
    },
    {
        "group": "Infraestrutura", "name": "Sistemas Operacionais e Linux", "slug": "sistemas-operacionais-linux", "icon": "🐧",
        "description": "Processos, memória, permissões e linha de comando.",
        "questions": [
            ("Qual comando lista os arquivos de um diretório no Linux?", "ls", ["cd", "rm", "mv"]),
            ("O Linux é, essencialmente:", "Um kernel de código aberto usado em várias distribuições",
             ["Um software de edição de imagens", "Um navegador", "Um jogo"]),
            ("Qual comando altera as permissões de um arquivo no Linux?", "chmod", ["ls", "pwd", "echo"]),
            ("O que é um processo em um sistema operacional?", "Um programa em execução",
             ["Um arquivo de texto", "Um tipo de disco", "Um driver de vídeo"]),
            ("O que faz o comando sudo?", "Executa um comando com privilégios de outro usuário, geralmente o root",
             ["Apaga o sistema", "Atualiza a BIOS", "Abre o navegador"]),
            ("O que é memória virtual?", "Uso de disco como extensão da memória RAM",
             ["Memória exclusiva da GPU", "Cache do processador", "Memória ROM da BIOS"]),
        ],
    },
    {
        "group": "Infraestrutura", "name": "Cloud Computing", "slug": "cloud-computing", "icon": "☁️",
        "description": "Computação em nuvem, modelos de serviço, serverless e CDN.",
        "questions": [
            ("Qual destes é um provedor de nuvem pública?", "Amazon Web Services (AWS)",
             ["Bloco de Notas", "Paint", "Calculadora"]),
            ("O que é computação em nuvem?", "Entrega de recursos de TI pela internet, sob demanda",
             ["Instalar servidores apenas locais", "Um tipo de antivírus", "Guardar dados só em pendrive"]),
            ("O que significa IaaS?", "Infraestrutura como serviço",
             ["Internet como serviço", "Interface como sistema", "Integração ao servidor"]),
            ("O que é escalabilidade na nuvem?", "Capacidade de aumentar ou reduzir recursos conforme a demanda",
             ["Diminuir a qualidade da imagem", "Ter um único servidor", "Proibir acessos"]),
            ("O que caracteriza uma arquitetura serverless?",
             "O provedor gerencia os servidores e você paga pela execução do código",
             ["Não usa nenhum computador", "O código roda só no navegador", "Exige comprar servidores físicos"]),
            ("O que é uma CDN?", "Rede que distribui cópias de conteúdo em locais próximos aos usuários",
             ["Um banco de dados relacional", "Um protocolo de e-mail", "Um tipo de firewall"]),
        ],
    },
    {
        "group": "Infraestrutura", "name": "DevOps e Containers", "slug": "devops-e-containers", "icon": "🚢",
        "description": "Docker, Kubernetes, CI/CD e infraestrutura como código.",
        "questions": [
            ("O Docker é usado para:", "Empacotar e executar aplicações em contêineres",
             ["Editar vídeos", "Criar planilhas", "Desenhar interfaces"]),
            ("O que significa DevOps?", "Integração entre desenvolvimento e operações",
             ["Design e Vendas", "Dados e Otimização", "Desktop e Office"]),
            ("O que é uma imagem Docker?", "Modelo somente leitura a partir do qual os contêineres são criados",
             ["Uma foto do servidor", "Um vídeo do deploy", "Um backup de banco de dados"]),
            ("O que significa CI/CD?", "Integração contínua e entrega/implantação contínuas",
             ["Controle de Internet e Dados", "Código Interno e Digital", "Cache Inteligente e Dinâmico"]),
            ("Qual ferramenta orquestra contêineres em larga escala?", "Kubernetes",
             ["Photoshop", "Git", "Excel"]),
            ("O que é Infraestrutura como Código (IaC)?",
             "Definir e provisionar infraestrutura por meio de arquivos versionáveis",
             ["Escrever código diretamente em servidores físicos", "Um tipo de virtualização de jogos",
              "Documentar a rede em papel"]),
        ],
    },
    {
        "group": "Infraestrutura", "name": "Hardware e Arquitetura de Computadores", "slug": "hardware-e-arquitetura", "icon": "🖥️",
        "description": "Processador, memórias, periféricos e representação de dados.",
        "questions": [
            ("Qual componente é considerado o 'cérebro' do computador?", "CPU (processador)",
             ["Fonte", "Gabinete", "Monitor"]),
            ("Qual memória é volátil, perdendo os dados ao desligar?", "RAM", ["SSD", "HD", "ROM"]),
            ("Quantos bits formam um byte?", "8", ["4", "16", "10"]),
            ("O que é uma GPU?", "Unidade de processamento gráfico",
             ["Unidade de gestão de portas", "Gerador de pulso universal", "Gravador de programas únicos"]),
            ("Qual é a função da memória cache do processador?",
             "Guardar dados acessados com frequência para acelerar o acesso",
             ["Armazenar arquivos do usuário", "Refrigerar o chip", "Conectar à internet"]),
            ("Qual é o valor decimal do binário 1010?", "10", ["8", "12", "14"]),
        ],
    },
    {
        "group": "Infraestrutura", "name": "IoT e Eletrônica", "slug": "iot-e-eletronica", "icon": "📡",
        "description": "Internet das Coisas, sensores, microcontroladores e protocolos.",
        "questions": [
            ("A sigla IoT significa:", "Internet das Coisas",
             ["Internet de Ouro", "Interface Ótica", "Integração Online Total"]),
            ("O Arduino é:", "Uma plataforma de prototipagem eletrônica com microcontrolador",
             ["Um sistema operacional", "Um navegador", "Um antivírus"]),
            ("O que é um sensor?", "Dispositivo que mede grandezas físicas e as converte em sinais",
             ["Um tipo de tela", "Um cabo de rede", "Um software de edição"]),
            ("O protocolo MQTT é muito usado em IoT por ser:", "Leve e baseado em publicar/assinar",
             ["Pesado, feito para transferir vídeos", "Exclusivo para e-mails", "Exclusivo para bancos de dados"]),
            ("O que é um microcontrolador?", "Um chip que reúne CPU, memória e periféricos para tarefas embarcadas",
             ["Um monitor de vídeo", "Um cabo especial", "Um tipo de HD"]),
            ("Para que serve o PWM em eletrônica?",
             "Controlar potência ou velocidade simulando níveis analógicos com pulsos digitais",
             ["Criptografar dados", "Compactar arquivos", "Nomear domínios"]),
        ],
    },
]
