# Cada pergunta: (texto, alternativa correta, [alternativas erradas]).
# A ordem define a pontuação: 2 fáceis (10), 2 médias (20), 2 difíceis (30).
G = "Desenvolvimento"

AREAS = [
    {
        "group": G, "name": "Lógica de Programação", "slug": "logica-de-programacao", "icon": "🧩",
        "description": "Algoritmos, variáveis, condições, laços e raciocínio lógico.",
        "questions": [
            ("O que é um algoritmo?", "Uma sequência finita de passos para resolver um problema",
             ["Um tipo de linguagem de programação", "Um componente físico do computador", "Um erro de execução do programa"]),
            ("Qual estrutura repete um bloco de código várias vezes?", "Laço de repetição (loop)",
             ["Comentário", "Declaração de variável", "Operador de atribuição"]),
            ("Qual é o resultado de 7 % 3 na maioria das linguagens?", "1", ["2", "0", "3"]),
            ("Um fluxograma serve principalmente para:", "Representar graficamente o fluxo de um algoritmo",
             ["Compilar o código-fonte", "Armazenar dados em disco", "Criptografar mensagens"]),
            ("Qual é o valor final de x? x←5; enquanto x>0 faça x←x−2", "-1", ["0", "1", "-2"]),
            ("Uma recursão sem caso base tende a causar:", "Estouro de pilha (stack overflow)",
             ["Uma compilação mais rápida", "Um laço finito", "Redução do uso de memória"]),
        ],
    },
    {
        "group": G, "name": "Python", "slug": "python", "icon": "🐍",
        "description": "Sintaxe, estruturas de dados e recursos da linguagem Python.",
        "questions": [
            ("Qual função exibe texto na tela em Python?", "print()", ["echo()", "console.log()", "printf()"]),
            ("Como se escreve um comentário de uma linha em Python?", "# comentário",
             ["// comentário", "/* comentário */", "-- comentário"]),
            ("Qual é o resultado de len([1, 2, 3, 4])?", "4", ["3", "5", "Erro"]),
            ("Qual estrutura de dados do Python é imutável?", "Tupla (tuple)",
             ["Lista (list)", "Dicionário (dict)", "Conjunto (set)"]),
            ("O que produz a expressão [x*x for x in range(4)]?", "[0, 1, 4, 9]",
             ["[1, 4, 9, 16]", "[0, 2, 4, 6]", "Um erro de sintaxe"]),
            ("No CPython, o que é o GIL (Global Interpreter Lock)?",
             "Um mecanismo que permite só uma thread executar bytecode Python por vez",
             ["Um gerenciador de pacotes", "Um otimizador que compila para C", "Uma biblioteca de interface gráfica"]),
        ],
    },
    {
        "group": G, "name": "JavaScript", "slug": "javascript", "icon": "🟨",
        "description": "A linguagem da web: variáveis, funções, assincronismo e DOM.",
        "questions": [
            ("Qual palavra-chave declara uma constante em JavaScript moderno?", "const", ["let", "var", "static"]),
            ("Qual método adiciona um item ao final de um array?", "push()", ["pop()", "shift()", "unshift()"]),
            ("Qual é o resultado de typeof null?", "\"object\"", ["\"null\"", "\"undefined\"", "\"number\""]),
            ("O operador === compara:", "Valor e tipo, sem conversão",
             ["Apenas o valor, com conversão de tipo", "Apenas o tipo", "Sempre referências de memória"]),
            ("O que uma Promise representa?", "O resultado futuro de uma operação assíncrona",
             ["Uma variável global protegida", "Um laço de repetição infinito", "Um módulo de estilos CSS"]),
            ("Em JavaScript, o que é uma closure?", "Uma função que mantém acesso ao escopo onde foi criada",
             ["Uma função que fecha o navegador", "Um método exclusivo de arrays", "Um erro de escopo em tempo de compilação"]),
        ],
    },
    {
        "group": G, "name": "Java", "slug": "java", "icon": "☕",
        "description": "Orientação a objetos, JVM e o ecossistema Java.",
        "questions": [
            ("Java é uma linguagem:", "Orientada a objetos e executada na JVM",
             ["Interpretada exclusivamente pelo navegador", "Usada apenas para bancos de dados", "Sem tipagem"]),
            ("Qual palavra-chave cria uma instância de uma classe em Java?", "new", ["this", "class", "extends"]),
            ("O ponto de entrada de uma aplicação Java é o método:", "public static void main(String[] args)",
             ["start()", "init()", "execute()"]),
            ("Qual palavra-chave é usada para herança de classes em Java?", "extends", ["implements", "inherits", "super"]),
            ("Qual é a função do Garbage Collector na JVM?", "Liberar memória de objetos que não são mais referenciados",
             ["Compilar o código-fonte", "Criptografar variáveis", "Gerenciar conexões de rede"]),
            ("Qual coleção NÃO admite elementos duplicados?", "HashSet", ["ArrayList", "LinkedList", "Vector"]),
        ],
    },
    {
        "group": G, "name": "C e C++", "slug": "c-e-cpp", "icon": "⚙️",
        "description": "Programação de baixo nível, ponteiros e gerenciamento de memória.",
        "questions": [
            ("Qual símbolo obtém o endereço de memória de uma variável em C?", "&", ["*", "#", "@"]),
            ("Qual função da biblioteca padrão de C exibe texto formatado?", "printf()", ["print()", "echo()", "cout()"]),
            ("Em C, o que é um ponteiro?", "Uma variável que armazena um endereço de memória",
             ["Um tipo de laço", "Uma função recursiva", "Um comentário especial"]),
            ("Qual a relação entre malloc e free?", "malloc aloca memória dinamicamente e free a libera",
             ["malloc libera e free aloca", "Ambos alocam memória na pilha", "Ambos servem para ler arquivos"]),
            ("Qual recurso existe em C++ e não existe em C?", "Classes e orientação a objetos",
             ["Ponteiros", "Funções", "Laços for"]),
            ("O que é RAII em C++?", "Vincular a vida de um recurso à vida de um objeto (construtor/destrutor)",
             ["Um compilador de código", "Uma biblioteca gráfica", "Um tipo de ponteiro nulo"]),
        ],
    },
    {
        "group": G, "name": "C# e .NET", "slug": "csharp-dotnet", "icon": "🔷",
        "description": "A linguagem C# e a plataforma .NET da Microsoft.",
        "questions": [
            ("C# foi desenvolvida pela:", "Microsoft", ["Oracle", "Google", "Apple"]),
            ("Qual é o ponto de entrada tradicional de um programa C#?", "Main", ["Start", "Init", "Run"]),
            ("O que é o .NET?", "Uma plataforma para desenvolver e executar aplicações",
             ["Um banco de dados", "Um sistema operacional", "Um navegador"]),
            ("O LINQ em C# serve para:", "Consultar coleções de dados com sintaxe integrada à linguagem",
             ["Compilar para código nativo em C++", "Criar interfaces móveis", "Gerenciar servidores Linux"]),
            ("Qual palavra-chave aguarda uma operação assíncrona em C#?", "await", ["yield", "defer", "wait"]),
            ("Em C#, qual a diferença entre struct e class?", "struct é tipo de valor e class é tipo de referência",
             ["struct é sempre maior que class", "class não pode ter métodos", "struct só existe em interfaces"]),
        ],
    },
    {
        "group": G, "name": "HTML e CSS", "slug": "html-e-css", "icon": "🎨",
        "description": "Estrutura e estilo de páginas web, layout e responsividade.",
        "questions": [
            ("HTML significa:", "HyperText Markup Language",
             ["High Text Machine Language", "Hyper Tool Multi Language", "HyperTransfer Markup Logic"]),
            ("Qual tag define o título de maior nível em uma página?", "<h1>", ["<title>", "<head>", "<h6>"]),
            ("Qual propriedade CSS altera a cor do texto?", "color",
             ["font-style", "text-decoration", "background-color"]),
            ("Qual recurso do CSS cria layouts em grade bidimensional?", "CSS Grid",
             ["float", "position: static", "display: inline"]),
            ("O que faz a meta tag viewport?", "Controla a largura e a escala da página em dispositivos móveis",
             ["Define o título da aba", "Carrega scripts externos", "Bloqueia o acesso de robôs"]),
            ("Qual seletor CSS tem MAIOR especificidade?", "Seletor de ID (#id)",
             ["Seletor de elemento (p)", "Seletor de classe (.classe)", "Seletor universal (*)"]),
        ],
    },
    {
        "group": G, "name": "Back-end e APIs", "slug": "backend-e-apis", "icon": "🔌",
        "description": "APIs REST, HTTP, autenticação e arquitetura de servidores.",
        "questions": [
            ("O que significa API?", "Application Programming Interface",
             ["Advanced Program Installation", "Automatic Protocol Internet", "Application Process Integration"]),
            ("Qual método HTTP é normalmente usado para buscar dados?", "GET", ["POST", "DELETE", "PUT"]),
            ("Qual código HTTP indica que o recurso não foi encontrado?", "404", ["200", "500", "301"]),
            ("Qual formato de dados é o mais usado em APIs REST?", "JSON", ["BMP", "MP3", "EXE"]),
            ("O que caracteriza uma API REST?",
             "Recursos identificados por URLs, operações via métodos HTTP e sem estado no servidor",
             ["Uso obrigatório de XML e SOAP", "Conexão permanente entre cliente e servidor",
              "Execução de código no navegador do cliente"]),
            ("Para que serve um JWT em uma API?", "Transportar, de forma assinada, dados de identidade e autorização",
             ["Comprimir imagens", "Criar tabelas em bancos de dados", "Compilar código no servidor"]),
        ],
    },
    {
        "group": G, "name": "Desenvolvimento Mobile", "slug": "desenvolvimento-mobile", "icon": "📱",
        "description": "Apps para Android e iOS, frameworks multiplataforma e PWAs.",
        "questions": [
            ("Qual linguagem é oficial no Android moderno, junto com Java?", "Kotlin", ["Swift", "Ruby", "Perl"]),
            ("Qual linguagem é usada nativamente em apps iOS modernos?", "Swift", ["Kotlin", "Go", "PHP"]),
            ("Qual linguagem o Flutter utiliza?", "Dart", ["Kotlin", "Swift", "C#"]),
            ("O React Native permite:", "Criar apps móveis usando JavaScript e React",
             ["Rodar apenas no navegador desktop", "Substituir o sistema Android", "Compilar apps só para Windows"]),
            ("O que é um app multiplataforma?", "Um único código-base que atende mais de um sistema operacional",
             ["Um app que só funciona sem internet", "Um app exclusivo de um fabricante",
              "Um app que dispensa a loja de aplicativos"]),
            ("O que é uma PWA?", "Aplicação web instalável que usa service workers e manifest",
             ["Um antivírus para celular", "Um formato de imagem", "Um banco de dados móvel"]),
        ],
    },
    {
        "group": G, "name": "Git e GitHub", "slug": "git-e-github", "icon": "🌿",
        "description": "Versionamento de código, branches e colaboração.",
        "questions": [
            ("Qual comando cria uma cópia local de um repositório remoto?", "git clone",
             ["git commit", "git init", "git push"]),
            ("Qual comando registra as mudanças preparadas no histórico local?", "git commit",
             ["git pull", "git add", "git status"]),
            ("O que faz o comando git add?", "Adiciona alterações à área de preparação (staging)",
             ["Envia ao servidor", "Apaga o histórico", "Cria uma branch"]),
            ("Qual comando envia commits locais ao repositório remoto?", "git push",
             ["git fetch", "git merge", "git stash"]),
            ("Qual a diferença entre git fetch e git pull?", "fetch só baixa as mudanças; pull baixa e integra à branch atual",
             ["fetch envia e pull apaga", "São idênticos", "pull só funciona em repositórios vazios"]),
            ("O que faz o git rebase?", "Reaplica commits sobre outra base, reescrevendo o histórico",
             ["Exclui o repositório remoto", "Apenas renomeia arquivos", "Cria uma tag de versão automática"]),
        ],
    },
    {
        "group": G, "name": "Estruturas de Dados e Algoritmos", "slug": "estruturas-de-dados", "icon": "🌳",
        "description": "Pilhas, filas, árvores, grafos, ordenação e complexidade.",
        "questions": [
            ("Qual estrutura segue a regra LIFO (último a entrar, primeiro a sair)?", "Pilha (stack)",
             ["Fila (queue)", "Lista ligada", "Árvore"]),
            ("Qual estrutura segue a regra FIFO (primeiro a entrar, primeiro a sair)?", "Fila (queue)",
             ["Pilha", "Heap", "Grafo"]),
            ("Qual é a complexidade da busca binária em um vetor ordenado?", "O(log n)", ["O(n)", "O(n²)", "O(1)"]),
            ("Uma tabela hash busca elementos, em média, em:", "O(1)", ["O(n)", "O(log n)", "O(n log n)"]),
            ("Qual algoritmo de ordenação tem complexidade O(n log n) no pior caso?", "Merge sort",
             ["Bubble sort", "Insertion sort", "Selection sort"]),
            ("Qual estrutura auxiliar é usada na busca em largura (BFS)?", "Fila",
             ["Pilha", "Tabela hash", "Heap máximo"]),
        ],
    },
    {
        "group": G, "name": "Engenharia de Software e Testes", "slug": "engenharia-de-software", "icon": "🛠️",
        "description": "Boas práticas, testes, modelagem e qualidade de software.",
        "questions": [
            ("O que é um teste unitário?", "Teste de uma pequena parte isolada do código, como uma função",
             ["Teste do sistema inteiro em produção", "Teste apenas visual", "Teste de carga da rede"]),
            ("O que significa a sigla UML?", "Unified Modeling Language",
             ["Universal Machine Logic", "User Management Layer", "Unique Model List"]),
            ("O que é refatoração?", "Melhorar a estrutura do código sem alterar seu comportamento externo",
             ["Adicionar novas funcionalidades", "Apagar o código antigo", "Traduzir o código para outra linguagem"]),
            ("O que é integração contínua (CI)?", "Integrar e testar o código automaticamente a cada mudança",
             ["Um tipo de banco de dados", "Um método de criptografia", "Um sistema de backup"]),
            ("O 'S' do princípio SOLID significa:", "Responsabilidade única (Single Responsibility)",
             ["Segurança total", "Simplicidade de sintaxe", "Servidor único"]),
            ("O que é TDD?", "Escrever os testes antes do código que os faz passar",
             ["Testar apenas após a entrega", "Um padrão de banco de dados", "Uma linguagem de testes"]),
        ],
    },
    {
        "group": G, "name": "Desenvolvimento de Jogos", "slug": "desenvolvimento-de-jogos", "icon": "🎮",
        "description": "Motores gráficos, game loop, física e gráficos em tempo real.",
        "questions": [
            ("Qual motor de jogos usa C# como linguagem principal de scripts?", "Unity",
             ["Unreal Engine", "Photoshop", "Blender"]),
            ("O que significa FPS em desempenho gráfico?", "Quadros por segundo",
             ["Fotos por sessão", "Formatos por sistema", "Filtros por sombra"]),
            ("Qual linguagem a Unreal Engine usa em seu código nativo?", "C++", ["Python", "Ruby", "Swift"]),
            ("O que é um game loop?", "Ciclo que processa entradas, atualiza o estado e renderiza continuamente",
             ["Um bug que trava o jogo", "Um tipo de textura", "Um servidor multiplayer"]),
            ("O que faz um shader?", "Programa executado na GPU que define como vértices e pixels são desenhados",
             ["Salva o progresso do jogo", "Compacta áudio", "Gerencia a rede"]),
            ("O que é delta time em jogos?", "Tempo entre dois quadros, para movimento independente do FPS",
             ["Tempo total da partida", "Latência do servidor", "Duração do áudio"]),
        ],
    },
]
