# Cada pergunta: (texto, alternativa correta, [alternativas erradas]).
# A ordem define a pontuação: 2 fáceis (10), 2 médias (20), 2 difíceis (30).
AREAS = [
    # ---------------- Segurança ----------------
    {
        "group": "Segurança e Criptografia", "name": "Segurança da Informação", "slug": "seguranca-da-informacao", "icon": "🛡️",
        "description": "Ameaças, boas práticas, autenticação e proteção de sistemas.",
        "questions": [
            ("Qual é uma boa prática para senhas?", "Usar senhas longas, únicas e um gerenciador de senhas",
             ["Repetir a mesma senha em todos os sites", "Usar a data de nascimento", "Anotar em um post-it no monitor"]),
            ("O que é phishing?", "Golpe que induz a vítima a fornecer dados por meio de mensagens falsas",
             ["Um tipo de firewall", "Uma atualização do sistema", "Um backup automático"]),
            ("O que é autenticação de dois fatores (2FA)?", "Uso de dois métodos distintos para confirmar a identidade",
             ["Duas senhas iguais", "Login em dois sites ao mesmo tempo", "Cópia da senha em dois locais"]),
            ("O que faz um firewall?", "Filtra o tráfego de rede conforme regras de segurança",
             ["Acelera o processador", "Recupera arquivos apagados", "Limpa o cache do navegador"]),
            ("Qual ataque insere comandos maliciosos em consultas a bancos de dados?", "SQL Injection",
             ["Ataque de negação de serviço (DDoS)", "Man-in-the-Middle", "Ransomware"]),
            ("Quais são as três propriedades da tríade CIA?", "Confidencialidade, Integridade e Disponibilidade",
             ["Controle, Identidade e Acesso", "Criptografia, Internet e Autenticação", "Cópia, Isolamento e Auditoria"]),
        ],
    },
    {
        "group": "Segurança e Criptografia", "name": "Criptografia e Blockchain", "slug": "criptografia-e-blockchain", "icon": "🔐",
        "description": "Chaves, hashes, assinaturas digitais, blockchain e contratos inteligentes.",
        "questions": [
            ("A criptografia serve para:", "Proteger a informação, tornando-a ilegível a quem não tem a chave",
             ["Acelerar downloads", "Aumentar o brilho da tela", "Apagar vírus"]),
            ("O que é blockchain?", "Cadeia de blocos de registros ligados por criptografia",
             ["Um tipo de pendrive", "Uma rede social", "Uma linguagem de programação"]),
            ("Na criptografia assimétrica, quantas chaves são usadas?", "Duas: uma pública e uma privada",
             ["Apenas uma", "Nenhuma", "Quatro"]),
            ("O que é um hash criptográfico?", "Resumo de tamanho fixo gerado a partir de dados",
             ["Uma chave privada", "Um tipo de backup", "Um certificado de site"]),
            ("O que é um contrato inteligente (smart contract)?",
             "Código que executa automaticamente regras registradas em uma blockchain",
             ["Um contrato impresso e assinado à mão", "Um antivírus", "Um aplicativo de banco"]),
            ("Qual destes é um algoritmo de criptografia simétrica?", "AES", ["RSA", "ECDSA", "Diffie-Hellman"]),
        ],
    },
    # ---------------- Design e Produto ----------------
    {
        "group": "Design e Produto", "name": "UX/UI Design", "slug": "ux-ui-design", "icon": "✏️",
        "description": "Experiência do usuário, interfaces, prototipagem e acessibilidade.",
        "questions": [
            ("UX significa:", "User Experience (experiência do usuário)",
             ["User Extension", "Unified Exchange", "Ultra Xray"]),
            ("O que é um wireframe?", "Esboço estrutural de uma tela, sem foco no visual final",
             ["Um código de banco de dados", "Um vídeo institucional", "Um teste de segurança"]),
            ("Qual ferramenta é muito usada para prototipar interfaces?", "Figma",
             ["Docker", "PostgreSQL", "Nginx"]),
            ("O que é acessibilidade digital?", "Garantir que pessoas com diferentes necessidades consigam usar o produto",
             ["Deixar o site mais rápido apenas", "Usar apenas cores escuras", "Bloquear o acesso por celular"]),
            ("Qual a razão mínima de contraste (WCAG AA) para texto normal?", "4,5:1", ["1,5:1", "2:1", "10:1"]),
            ("O que é um teste de usabilidade?", "Observar usuários reais realizando tarefas para achar problemas de uso",
             ["Medir o consumo de energia", "Testar a velocidade do servidor", "Revisar o código-fonte"]),
        ],
    },
    # ---------------- Gestão e Negócios ----------------
    {
        "group": "Gestão e Negócios", "name": "Gestão de Projetos e Métodos Ágeis", "slug": "gestao-de-projetos-ageis", "icon": "📋",
        "description": "Scrum, Kanban, backlog, sprints e entrega de valor.",
        "questions": [
            ("Qual framework ágil organiza o trabalho em sprints?", "Scrum", ["ITIL", "COBIT", "UML"]),
            ("Um quadro Kanban organiza as tarefas em:", "Colunas por etapa do fluxo de trabalho",
             ["Apenas uma lista", "Gráficos de pizza", "Tabelas de banco de dados"]),
            ("Quem prioriza o backlog do produto no Scrum?", "O Product Owner",
             ["O Scrum Master", "O testador", "O cliente final, sempre"]),
            ("Qual é a duração típica de uma sprint?", "De 1 a 4 semanas", ["1 dia", "6 meses", "Não tem prazo definido"]),
            ("O que é um MVP?", "Produto Mínimo Viável: versão inicial para validar a ideia",
             ["Melhor Versão Possível, já final", "Módulo de Vendas Pago", "Modelo Visual Padrão"]),
            ("Qual é o objetivo da retrospectiva da sprint?", "Refletir sobre o trabalho e melhorar o processo da equipe",
             ["Demitir integrantes", "Apresentar o produto só ao cliente", "Planejar as férias"]),
        ],
    },
    {
        "group": "Gestão e Negócios", "name": "Governança de TI, ITIL e LGPD", "slug": "governanca-ti-lgpd", "icon": "⚖️",
        "description": "Boas práticas de governança, gestão de serviços e proteção de dados pessoais.",
        "questions": [
            ("A LGPD é a lei brasileira de:", "Proteção de dados pessoais",
             ["Direitos autorais de software", "Impostos sobre tecnologia", "Registro de domínios"]),
            ("O que é um dado pessoal, segundo a LGPD?",
             "Informação relacionada a uma pessoa natural identificada ou identificável",
             ["Apenas o CPF", "Somente senhas", "Apenas dados de empresas"]),
            ("Quem é o controlador de dados na LGPD?", "Quem toma as decisões sobre o tratamento dos dados pessoais",
             ["Quem apenas guarda os backups", "O titular dos dados, sempre", "O invasor do sistema"]),
            ("O ITIL é um conjunto de boas práticas para:", "Gerenciamento de serviços de TI",
             ["Desenvolvimento de jogos", "Design gráfico", "Fabricação de hardware"]),
            ("Qual órgão fiscaliza a LGPD no Brasil?", "ANPD", ["ANATEL", "CADE", "ABNT"]),
            ("O que é o COBIT?", "Um framework de governança e gestão de TI",
             ["Uma linguagem de programação", "Um sistema operacional", "Um banco de dados NoSQL"]),
        ],
    },
    {
        "group": "Gestão e Negócios", "name": "Empreendedorismo e Startups", "slug": "empreendedorismo-e-startups", "icon": "🚀",
        "description": "Modelos de negócio, validação de ideias e startups de tecnologia.",
        "questions": [
            ("O que é uma startup?", "Empresa nascente, geralmente inovadora, com modelo de negócio escalável",
             ["Toda empresa antiga", "Uma loja física comum", "Um órgão público"]),
            ("O que é um modelo de negócio?", "A forma como a empresa cria, entrega e captura valor",
             ["O logotipo da empresa", "O contrato de trabalho", "A planta do escritório"]),
            ("O que é um 'pitch'?", "Apresentação curta para convencer investidores ou clientes",
             ["Um tipo de código", "Um relatório fiscal", "Um contrato"]),
            ("O que significa um negócio ser 'escalável'?", "Crescer a receita sem crescer os custos na mesma proporção",
             ["Ter muitos funcionários", "Ter escritório grande", "Vender apenas localmente"]),
            ("O que é o Business Model Canvas?", "Quadro visual de 9 blocos que descreve um modelo de negócio",
             ["Um software de desenho 3D", "Uma planilha contábil oficial", "Um contrato padrão"]),
            ("O que é 'burn rate'?", "A velocidade com que a empresa consome seu caixa",
             ["A taxa de juros do banco", "A velocidade do servidor", "O lucro mensal"]),
        ],
    },
    # ---------------- Fundamentos e Suporte ----------------
    {
        "group": "Fundamentos e Suporte", "name": "Suporte Técnico e Informática Básica", "slug": "suporte-e-informatica-basica", "icon": "💻",
        "description": "Uso do computador, Office, diagnóstico de problemas e backup.",
        "questions": [
            ("Qual atalho copia o item selecionado no Windows?", "Ctrl + C", ["Ctrl + V", "Ctrl + Z", "Ctrl + P"]),
            ("Qual é a extensão comum de arquivos do Word?", ".docx", [".xlsx", ".pptx", ".jpg"]),
            ("Qual função do Excel soma os valores de um intervalo?", "SOMA (SUM)",
             ["MÉDIA (AVERAGE)", "CONT.SE (COUNTIF)", "PROCV (VLOOKUP)"]),
            ("O que verificar primeiro quando um computador não liga?", "Cabo de energia, tomada e fonte",
             ["Formatar o sistema", "Trocar o processador", "Comprar outro computador"]),
            ("O que é um driver?", "Software que permite ao sistema operacional usar um hardware",
             ["Um cabo", "Um tipo de vírus", "Uma extensão de arquivo"]),
            ("Qual a diferença entre backup completo e incremental?", "O incremental copia só o que mudou desde o último backup",
             ["O completo copia só arquivos novos", "São idênticos", "O incremental apaga os dados originais"]),
        ],
    },
    {
        "group": "Fundamentos e Suporte", "name": "Matemática para Computação", "slug": "matematica-para-computacao", "icon": "➗",
        "description": "Bases numéricas, lógica booleana, potências, logaritmos e combinatória.",
        "questions": [
            ("Quanto é 2 elevado a 10?", "1024", ["1000", "512", "2048"]),
            ("Qual é o resultado de 15 mod 4?", "3", ["1", "4", "0"]),
            ("Na lógica booleana, a operação AND resulta em verdadeiro quando:", "Ambas as entradas são verdadeiras",
             ["Ao menos uma entrada é verdadeira", "Ambas as entradas são falsas", "As entradas são diferentes"]),
            ("O número decimal 13 em binário é:", "1101", ["1011", "1110", "1001"]),
            ("Qual é o valor de log₂(8)?", "3", ["2", "4", "8"]),
            ("Quantos subconjuntos possui um conjunto de 4 elementos?", "16", ["8", "4", "24"]),
        ],
    },
    {
        "group": "Fundamentos e Suporte", "name": "Tecnologias Emergentes", "slug": "tecnologias-emergentes", "icon": "🔭",
        "description": "5G, realidade aumentada, computação quântica, impressão 3D e edge computing.",
        "questions": [
            ("O que significa 5G?", "Quinta geração de redes móveis",
             ["Cinco gigabytes", "Quinto Google", "Cinco gateways"]),
            ("Qual tecnologia sobrepõe elementos virtuais ao mundo real?", "Realidade aumentada (AR)",
             ["Impressão 3D", "Blockchain", "Computação em nuvem"]),
            ("O que é computação quântica?", "Computação que usa princípios da mecânica quântica, como os qubits",
             ["Computação em nuvem", "Computação sem energia", "Um tipo de HD"]),
            ("O que faz uma impressora 3D?", "Constrói objetos adicionando material camada por camada",
             ["Imprime apenas em papel", "Corta o material", "Escaneia documentos"]),
            ("O que é um gêmeo digital (digital twin)?",
             "Réplica virtual de um objeto ou sistema físico, atualizada com dados reais",
             ["Um clone de e-mail", "Um backup de site", "Um par de monitores"]),
            ("O que é computação de borda (edge computing)?", "Processar dados perto de onde são gerados, reduzindo a latência",
             ["Processar tudo em um único datacenter distante", "Computar apenas nos cabos", "Desligar os sensores"]),
        ],
    },
]
